apiVersion: v1
kind: Service
metadata:
  name: backend-srv
  namespace: tabimworld-staging
spec:
  selector:
    app: backend-depl
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
