apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-secret
  annotations:
    kubernetes.io/service-account.name: github-actions
type: kubernetes.io/service-account-token
