apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
  namespace: tabimworld-prod
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-depl
  template:
    metadata:
      labels:
        app: backend-depl
    spec:
      containers:
        - name: headless
          image: ghcr.io/tabimworld/backend:main-ae8f7fe-1684680718 # {"$imagepolicy": "tabimworld-prod:tabimworld-backend"}
          envFrom:
            - secretRef:
                name: backend-env
            - configMapRef:
                name: backend-env
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: tabimworld-backend
  namespace: tabimworld-prod
spec:
  image: ghcr.io/tabimworld/backend
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: tabimworld-backend
  namespace: tabimworld-prod
spec:
  imageRepositoryRef:
    name: tabimworld-backend
  policy:
    semver:
      range: '>=0.1.0'
